In [1]:
import numpy as np
import pandas as pd

data = pd.read_csv("https://project-employees.s3.amazonaws.com/employeeinfo.csv")

In [2]:
data = data.drop(['EmployeeCount','EmployeeNumber','Over18','StandardHours'],axis=1)
data.loc[data['Attrition']=='No','Attrition'] = 0
data.loc[data['Attrition']=='Yes','Attrition'] = 1
data.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,Gender,...,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,1,Travel_Rarely,1102,Sales,1,2,Life Sciences,2,Female,...,3,1,0,8,0,1,6,4,0,5
1,49,0,Travel_Frequently,279,Research & Development,8,1,Life Sciences,3,Male,...,4,4,1,10,3,3,10,7,1,7
2,37,1,Travel_Rarely,1373,Research & Development,2,2,Other,4,Male,...,3,2,0,7,3,3,0,0,0,0
3,33,0,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,4,Female,...,3,3,0,8,3,3,8,7,3,0
4,27,0,Travel_Rarely,591,Research & Development,2,1,Medical,1,Male,...,3,4,1,6,3,3,2,2,2,2

In [3]:
data['Business_Travel_Rarely']=0
data['Business_Travel_Frequently']=0
data['Business_Non-Travel']=0

data.loc[data['BusinessTravel']=='Travel_Rarely','Business_Travel_Rarely'] = 1
data.loc[data['BusinessTravel']=='Travel_Frequently','Business_Travel_Frequently'] = 1
data.loc[data['BusinessTravel']=='Non-Travel','Business_Non-Travel'] = 1

In [4]:
data['Life Sciences']=0
data['Medical']=0
data['Marketing']=0
data['Technical Degree']=0
data['Education Human Resources']=0
data['Education_Other']=0

data.loc[data['EducationField']=='Life Sciences','Life Sciences'] = 1
data.loc[data['EducationField']=='Medical','Medical'] = 1
data.loc[data['EducationField']=='Other','Education_Other'] = 1
data.loc[data['EducationField']=='Technical Degree','Technical Degree'] = 1
data.loc[data['EducationField']=='Human Resources','Education Human Resources'] = 1
data.loc[data['EducationField']=='Marketing','Marketing'] = 1

In [5]:
data['Sales']=0
data['R&D']=0
data['Dept_Human Resources'] =0

data.loc[data['Department']=='Sales','Sales'] = 1
data.loc[data['Department']=='Research & Development','R&D'] = 1
data.loc[data['Department']=='Human Resources','Dept_Human Resources'] = 1

In [6]:
data.loc[data['Gender']=='Male','Gender'] = 1
data.loc[data['Gender']=='Female','Gender'] = 0

In [7]:
data['Research Scientist']=0
data['Laboratory Technician']=0
data['Sales Executive']=0
data['Manufacturing Director']=0
data['Healthcare Representative']=0
data['Sales Representative']=0
data['Research Director']=0
data['Manager'] = 0
data['Job_Human_Resources'] = 0

data.loc[data['JobRole']=='Research Scientist','Research Scientist'] = 1
data.loc[data['JobRole']=='Laboratory Technician','Laboratory Technician'] = 1
data.loc[data['JobRole']=='Sales Executive','Sales Executive'] = 1
data.loc[data['JobRole']=='Sales Representative','Sales Representative'] = 1
data.loc[data['JobRole']=='Manufacturing Director','Manufacturing Director'] = 1
data.loc[data['JobRole']=='Healthcare Representative','Healthcare Representative'] = 1
data.loc[data['JobRole']=='Research Director','Research Director'] = 1
data.loc[data['JobRole']=='Manager','Manager'] = 1
data.loc[data['JobRole']=='Human Resources','Job_Human_Resources'] = 1
data.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,Gender,...,Dept_Human Resources,Research Scientist,Laboratory Technician,Sales Executive,Manufacturing Director,Healthcare Representative,Sales Representative,Research Director,Manager,Job_Human_Resources
0,41,1,Travel_Rarely,1102,Sales,1,2,Life Sciences,2,0,...,0,0,0,1,0,0,0,0,0,0
1,49,0,Travel_Frequently,279,Research & Development,8,1,Life Sciences,3,1,...,0,1,0,0,0,0,0,0,0,0
2,37,1,Travel_Rarely,1373,Research & Development,2,2,Other,4,1,...,0,0,1,0,0,0,0,0,0,0
3,33,0,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,4,0,...,0,1,0,0,0,0,0,0,0,0
4,27,0,Travel_Rarely,591,Research & Development,2,1,Medical,1,1,...,0,0,1,0,0,0,0,0,0,0

In [8]:
data['Marital_single']=0
data['Marital_married']=0
data['Marital_divorced']=0

data.loc[data['MaritalStatus']=='Married','Marital_married'] = 1
data.loc[data['MaritalStatus']=='Single','Marital_single'] = 1
data.loc[data['MaritalStatus']=='Divorced','Marital_divorced'] = 1

In [9]:
data.loc[data['OverTime']=='No','OverTime'] = 0
data.loc[data['OverTime']=='Yes','OverTime'] = 1
data.head()

data['Attrition'] = data['Attrition'].astype('int')
data['Gender'] = data['Gender'].astype('int')
data['OverTime'] = data['OverTime'].astype('int')

In [10]:
data

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,Gender,...,Sales Executive,Manufacturing Director,Healthcare Representative,Sales Representative,Research Director,Manager,Job_Human_Resources,Marital_single,Marital_married,Marital_divorced
0,41,1,Travel_Rarely,1102,Sales,1,2,Life Sciences,2,0,...,1,0,0,0,0,0,0,1,0,0
1,49,0,Travel_Frequently,279,Research & Development,8,1,Life Sciences,3,1,...,0,0,0,0,0,0,0,0,1,0
2,37,1,Travel_Rarely,1373,Research & Development,2,2,Other,4,1,...,0,0,0,0,0,0,0,1,0,0
3,33,0,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,4,0,...,0,0,0,0,0,0,0,0,1,0
4,27,0,Travel_Rarely,591,Research & Development,2,1,Medical,1,1,...,0,0,0,0,0,0,0,0,1,0
5,32,0,Travel_Frequently,1005,Research & Development,2,2,Life Sciences,4,1,...,0,0,0,0,0,0,0,1,0,0
6,59,0,Travel_Rarely,1324,Research & Development,3,3,Medical,3,0,...,0,0,0,0,0,0,0,0,1,0
7,30,0,Travel_Rarely,1358,Research & Development,24,1,Life Sciences,4,1,...,0,0,0,0,0,0,0,0,0,1
8,38,0,Travel_Frequently,216,Research & Development,23,3,Life Sciences,4,1,...,0,1,0,0,0,0,0,1,0,0
9,36,0,Travel_Rarely,1299,Research & Development,27,3,Medical,3,1,...,0,0,1,0,0,0,0,0,1,0
10,35,0,Travel_Rarely,809,Research & Development,16,3,Medical,1,1,...,0,0,0,0,0,0,0,0,1,0
11,29,0,Travel_Rarely,153,Research & Development,15,2,Life Sciences,4,0,...,0,0,0,0,0,0,0,1,0,0
12,31,0,Travel_Rarely,670,Research & Development,26,1,Life Sciences,1,1,...,0,0,0,0,0,0,0,0,0,1
13,34,0,Travel_Rarely,1346,Research & Development,19,2,Medical,2,1,...,0,0,0,0,0,0,0,0,0,1
14,28,1,Travel_Rarely,103,Research & Development,24,3,Life Sciences,3,1,...,0,0,0,0,0,0,0,1,0,0
15,29,0,Travel_Rarely,1389,Research & Development,21,4,Life Sciences,2,0,...,0,1,0,0,0,0,0,0,0,1
16,32,0,Travel_Rarely,334,Research & Development,5,2,Life Sciences,1,1,...,0,0,0,0,0,0,0,0,0,1
17,22,0,Non-Travel,1123,Research & Development,16,2,Medical,4,1,...,0,0,0,0,0,0,0,0,0,1
18,53,0,Travel_Rarely,1219,Sales,2,4,Life Sciences,1,0,...,0,0,0,0,0,1,0,0,1,0
19,38,0,Travel_Rarely,371,Research & Development,2,3,Life Sciences,4,1,...,0,0,0,0,0,0,0,1,0,0
20,24,0,Non-Travel,673,Research & Development,11,2,Other,1,0,...,0,1,0,0,0,0,0,0,0,1
21,36,1,Travel_Rarely,1218,Sales,9,4,Life Sciences,3,1,...,0,0,0,1,0,0,0,1,0,0
22,34,0,Travel_Rarely,419,Research & Development,7,4,Life Sciences,1,0,...,0,0,0,0,1,0,0,1,0,0
23,21,0,Travel_Rarely,391,Research & Development,15,2,Life Sciences,3,1,...,0,0,0,0,0,0,0,1,0,0
24,34,1,Travel_Rarely,699,Research & Development,6,1,Medical,2,1,...,0,0,0,0,0,0,0,1,0,0
25,53,0,Travel_Rarely,1282,Research & Development,5,3,Other,3,0,...,0,0,0,0,0,1,0,0,0,1
26,32,1,Travel_Frequently,1125,Research & Development,16,1,Life Sciences,2,0,...,0,0,0,0,0,0,0,1,0,0
27,42,0,Travel_Rarely,691,Sales,8,4,Marketing,3,1,...,1,0,0,0,0,0,0,0,1,0
28,44,0,Travel_Rarely,477,Research & Development,7,4,Medical,1,0,...,0,0,1,0,0,0,0,0,1,0
29,46,0,Travel_Rarely,705,Sales,2,4,Marketing,2,0,...,0,0,0,0,0,1,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1440,36,0,Travel_Frequently,688,Research & Development,4,2,Life Sciences,4,0,...,0,1,0,0,0,0,0,0,0,1
1441,56,0,Non-Travel,667,Research & Development,1,4,Life Sciences,3,1,...,0,0,1,0,0,0,0,0,0,1
1442,29,1,Travel_Rarely,1092,Research & Development,1,4,Medical,1,1,...,0,0,0,0,0,0,0,0,1,0
1443,42,0,Travel_Rarely,300,Research & Development,2,3,Life Sciences,1,1,...,0,0,0,0,0,1,0,0,1,0
1444,56,1,Travel_Rarely,310,Research & Development,7,2,Technical Degree,4,1,...,0,0,0,0,0,0,0,0,1,0
1445,41,0,Travel_Rarely,582,Research & Development,28,4,Life Sciences,1,0,...,0,1,0,0,0,0,0,0,1,0
1446,34,0,Travel_Rarely,704,Sales,28,3,Marketing,4,0,...,1,0,0,0,0,0,0,0,1,0
1447,36,0,Non-Travel,301,Sales,15,4,Marketing,4,1,...,1,0,0,0,0,0,0,0,0,1
1448,41,0,Travel_Rarely,930,Sales,3,3,Life Sciences,3,1,...,1,0,0,0,0,0,0,0,0,1
1449,32,0,Travel_Rarely,529,Research & Development,2,3,Technical Degree,4,1,...,0,0,0,0,0,0,0,1,0,0
1450,35,0,Travel_Rarely,1146,Human Resources,26,4,Life Sciences,3,0,...,0,0,0,0,0,0,1,1,0,0
1451,38,0,Travel_Rarely,345,Sales,10,2,Life Sciences,1,0,...,1,0,0,0,0,0,0,0,1,0
1452,50,1,Travel_Frequently,878,Sales,1,4,Life Sciences,2,1,...,1,0,0,0,0,0,0,0,0,1
1453,36,0,Travel_Rarely,1120,Sales,11,4,Marketing,2,0,...,1,0,0,0,0,0,0,0,1,0
1454,45,0,Travel_Rarely,374,Sales,20,3,Life Sciences,4,0,...,1,0,0,0,0,0,0,1,0,0
1455,40,0,Travel_Rarely,1322,Research & Development,2,4,Life Sciences,3,1,...,0,0,0,0,0,0,0,1,0,0
1456,35,0,Travel_Frequently,1199,Research & Development,18,4,Life Sciences,3,1,...,0,0,1,0,0,0,0,0,1,0
1457,40,0,Travel_Rarely,1194,Research & Development,2,4,Medical,3,0,...,0,0,0,0,0,0,0,0,1,0
1458,35,0,Travel_Rarely,287,Research & Development,1,4,Life Sciences,3,0,...,0,0,0,0,0,0,0,0,1,0
1459,29,0,Travel_Rarely,1378,Research & Development,13,2,Other,4,1,...,0,0,0,0,0,0,0,0,1,0
1460,29,0,Travel_Rarely,468,Research & Development,28,4,Medical,4,0,...,0,0,0,0,0,0,0,1,0,0
1461,50,1,Travel_Rarely,410,Sales,28,3,Marketing,4,1,...,1,0,0,0,0,0,0,0,0,1
1462,39,0,Travel_Rarely,722,Sales,24,1,Marketing,2,0,...,1,0,0,0,0,0,0,0,1,0
1463,31,0,Non-Travel,325,Research & Development,5,3,Medical,2,1,...,0,1,0,0,0,0,0,1,0,0
1464,26,0,Travel_Rarely,1167,Sales,5,3,Other,4,0,...,0,0,0,1,0,0,0,1,0,0
1465,36,0,Travel_Frequently,884,Research & Development,23,2,Medical,3,1,...,0,0,0,0,0,0,0,0,1,0
1466,39,0,Travel_Rarely,613,Research & Development,6,1,Medical,4,1,...,0,0,1,0,0,0,0,0,1,0
1467,27,0,Travel_Rarely,155,Research & Development,4,3,Life Sciences,2,1,...,0,1,0,0,0,0,0,0,1,0
1468,49,0,Travel_Frequently,1023,Sales,2,3,Medical,4,1,...,1,0,0,0,0,0,0,0,1,0
1469,34,0,Travel_Rarely,628,Research & Development,8,3,Medical,2,1,...,0,0,0,0,0,0,0,0,1,0

In [11]:
from pycaret.classification import *
sd1=setup(data,target='Attrition')

ImportError: No module named 'pycaret'

In [12]:
compare_models()

NameError: name 'compare_models' is not defined

In [13]:
sd1 = create_model('ridge')

NameError: name 'create_model' is not defined

In [14]:
evaluate_model(sd1)
sd1=tune_model(sd1)

NameError: name 'evaluate_model' is not defined

In [15]:
save_model(lr, model_name = 'C:\Users\GagaN\Desktop\MLproject1')

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (<ipython-input-15-d48cda768b19>, line 1)